const emoji={Burgers:'🍔',Pizza:'🍕',Biryani:'🍗',Indian:'🍛','Chinese':'🍜','South Indian':'🥘','Rolls & Shawarma':'🌯','Fast Food':'🍟',Momos:'🥟',Desserts:'🍰',Drinks:'🥤'};
const categories=['All',...new Set(items.map(x=>x.category))]; let selected='All',cart=[];
function renderCategories(){document.getElementById('categories').innerHTML=categories.slice(1).map(c=>`<button class="cat" onclick="filterCategory('${c}')">${emoji[c]||'🍽️'} ${c}</button>`).join('')}
function renderFilters(){document.getElementById('filters').innerHTML=categories.map(c=>`<button class="filter ${c===selected?'active':''}" onclick="filterCategory('${c}')">${c}</button>`).join('')}
function renderRestaurants(list=restaurants){document.getElementById('restaurantResultCount').textContent=list.length+' restaurants';document.getElementById('restaurants').innerHTML=list.map((r,i)=>`<article class="restaurant"><div class="rest-img">${['🍛','🌶️','🍗','🥘','🥞','🍽️','🍕','🧀','🍔','🍟','🍜','🥢','🌯','🥟','🍰','🍫','🧃','☕','🥗','🌮'][i%20]}</div><span class="offer">${r.offer} OFF</span><h3>${r.name}</h3><div class="rating">★ ${r.rating}</div><div class="muted">${r.cuisine}</div><p class="muted">📍 ${r.area}, ${r.city}, ${r.state}<br>🕐 ${r.time} • 🚚 ${r.delivery}<br>💰 ${r.cost}</p><button onclick="showRestaurant('${r.name.replace(/'/g,"\\'")}')">View Restaurant</button></article>`).join('')}
function renderMenu(list=items){document.getElementById('resultCount').textContent=list.length+' items';document.getElementById('menuGrid').innerHTML=list.map((x,i)=>`<article class="card"><div class="food-img">${emoji[x.category]||'🍽️'}</div><div class="tag">${x.category} • ${x.restaurant}</div><h3>${x.name}</h3><div class="rating">★ ${x.rating}</div><p class="muted">${x.description}</p><div class="price">₹${x.price}</div><button class="add" onclick="addCartByItem(${items.indexOf(x)})">ADD</button></article>`).join('')}
function filterCategory(c){selected=c;renderFilters();let list=c==='All'?items:items.filter(x=>x.category===c);renderMenu(list);document.getElementById('menu').scrollIntoView({behavior:'smooth'})}
function doSearch(){let q=document.getElementById('search').value.toLowerCase().trim();selected='All';renderFilters();if(!q){renderRestaurants();renderMenu();return}let rlist=restaurants.filter(r=>[r.name,r.cuisine,r.city,r.state,r.area,r.address].join(' ').toLowerCase().includes(q));let ilist=items.filter(x=>[x.name,x.category,x.restaurant,x.description].join(' ').toLowerCase().includes(q));renderRestaurants(rlist);renderMenu(ilist);document.getElementById('places').scrollIntoView({behavior:'smooth'})}
function showRestaurant(name){let r=restaurants.find(x=>x.name===name), menuItems=items.filter(x=>x.restaurant===name);document.getElementById('menuGrid').innerHTML=`<div style="grid-column:1/-1;background:white;padding:25px;border-radius:18px"><h2>${r.name}</h2><p class="muted">★ ${r.rating} • ${r.cuisine}<br>📍 ${r.address}<br>🕐 ${r.time} • 🚚 ${r.delivery}<br>💰 ${r.cost}<br>🏷️ ${r.offer} OFF</p><h3>Menu</h3>${menuItems.length?menuItems.map(x=>`<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eee"><span>${emoji[x.category]||'🍽️'} ${x.name}<small class="muted"> — ${x.description}</small></span><b>₹${x.price}</b></div>`).join(''):'<p class="muted">Menu items will be added soon.</p>'}</div>`;document.getElementById('menu').scrollIntoView({behavior:'smooth'})}
function addCartByItem(i){cart.push(items[i]);updateCart();toggleCart(true)}
function updateCart(){document.getElementById('cartCount').textContent=cart.length;let box=document.getElementById('cartItems');box.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span style="font-size:28px">${emoji[x.category]||'🍽️'}</span><div style="flex:1"><b>${x.name}</b><div class="muted">₹${x.price}</div></div><button onclick="removeCart(${i})">Remove</button></div>`).join(''):'<p class="muted">Your cart is empty.</p>';let sub=cart.reduce((a,x)=>a+x.price,0),tax=Math.round(sub*.05);document.getElementById('subtotal').textContent='₹'+sub;document.getElementById('taxes').textContent='₹'+tax;document.getElementById('total').textContent='₹'+(sub+tax+(cart.length?40:0))}
function removeCart(i){cart.splice(i,1);updateCart()} function toggleCart(force){let p=document.getElementById('cartPanel'),o=document.getElementById('overlay'),open=force===true||!p.classList.contains('open');p.classList.toggle('open',open);o.classList.toggle('open',open)}
document.getElementById('cartBtn').onclick=()=>toggleCart();document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});renderCategories();renderFilters();renderRestaurants();renderMenu();updateCart();